# Generated by Django 5.0.1 on 2025-02-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedded',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='embedded',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='embedded',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
