# Generated by Django 5.0.1 on 2025-03-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddeds', '0003_alter_embedded_options_remove_embedded_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedded',
            name='CLIENT_ID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='embedded',
            name='CLIENT_SECRET',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='embedded',
            name='DATASET_ID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='embedded',
            name='REPORT_ID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='embedded',
            name='TENANT_ID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='embedded',
            name='WORKSPACE_ID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
