# Generated by Django 5.0.1 on 2025-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddeds', '0002_alter_embedded_options_embedded_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedded',
            options={'ordering': ['CLIENT_ID']},
        ),
        migrations.RemoveField(
            model_name='embedded',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='embedded',
            name='description',
        ),
        migrations.RemoveField(
            model_name='embedded',
            name='name',
        ),
        migrations.RemoveField(
            model_name='embedded',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='embedded',
            name='CLIENT_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='embedded',
            name='CLIENT_SECRET',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='embedded',
            name='DATASET_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='embedded',
            name='REPORT_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='embedded',
            name='TENANT_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='embedded',
            name='WORKSPACE_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
