# Generated by Django 5.0.1 on 2025-03-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clienteshtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOKEN_UUID', models.CharField(blank=True, max_length=200, null=True)),
                ('CLIENT_HTML', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['TOKEN_UUID'],
            },
        ),
    ]
