# Generated by Django 5.0.1 on 2025-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteshtmls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteshtml',
            name='EMBED_TOKEN',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clienteshtml',
            name='EMBED_URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clienteshtml',
            name='REPORT_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clienteshtml',
            name='WORKSPACE_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clienteshtml',
            name='CLIENT_HTML',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clienteshtml',
            name='TOKEN_UUID',
            field=models.UUIDField(),
        ),
    ]
