# Generated by Django 5.0.1 on 2025-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteshtmls', '0006_alter_clienteshtml_client_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteshtml',
            name='EMBED_TOKEN',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='clienteshtml',
            name='EMBED_URL',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
